### ISSUE TITLE
3차 세미나 실습 및 과제

### ISSUE THREAD

**Issue by chaentopia** [GO-SOPT-iOS-Part/ChungChaeEun#5]
## Description
- 3차 세미나 과제
- TVING 메인 및 마이 페이지 구현

## To-do
기본과제
- [x] 마이페이지 구현
- [x] 메인페이지 버튼 구현
- [x] Main->My 로직 추가
심화과제
- [ ] 메인페이지 전체 UI 구현 (셀 수평 스크롤)
- [ ] 스크롤로 뷰컨 이동
- [ ] 이미지 스크롤 구현
